all: main

main:   
	gcc -Wall -Werror conversao_de_bases.c -lm -o conversao_de_bases.out	
# para o windows comentar a linha acima e descomentar a linha abaixo
#  gcc conversao_de_bases.c -lm conversao_de_bases.exe 	 	

run:
	./conversao_de_bases.out	

clean:
	rm -f conversao_de_bases.out *.o	
# para o windows comentar a linha acima e descomentar a linha abaixo
#del bin\app_main.exe obj\*.o 	 	